name: NodeJS CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: hidrosolcm
          MYSQL_PASSWORD: mysql
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      MYSQL_HOST: locahost
      MYSQL_PORT: 3306
      MYSQL_DATABASE: 'hidrosolcm'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'mysql'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: actions/setup-node@v3
        with:
          node-version: '20'
        
      - name: "Instala o docker no Github actions"
        run: |
         sudo apt-get update
         sudo apt-get install -y docker-ce-cli

      - name: Build and test Node.js app in Docker
        run: |
          # Construa a imagem Docker
          docker build -t hidrosolserver .
          # Execute os testes dentro do contêiner
          docker run hidrosolserver npm run test:ci
